#! /usr/bin/bash

#echo $1 $2 $3 ' -> echo $1 $2 $3'
if [ $1 = s ] ; then
echo Running server. Please wait...
python3 manage.py runserver 
fi
if [ $1 = ? ] ; then
echo 'USE ./run with m to migrate, with s to run server'
fi
if [ $1 = m ] ; then
echo Migrating. Please wait...
python3 manage.py migrate
fi
