# Generated by Django 3.1.4 on 2020-12-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('Ownership', models.CharField(choices=[('P', 'Private'), ('R', 'Royal'), ('M', 'Museum')], default='P', max_length=1)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gem')),
            ],
        ),
    ]
