# Generated by Django 3.1.4 on 2020-12-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201214_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='weight',
        ),
        migrations.AddField(
            model_name='sell',
            name='city',
            field=models.CharField(default='NYC', max_length=50),
            preserve_default=False,
        ),
    ]
